name: action de base

on:
  push: ~
  workflow_dispatch:
    inputs:
      environment:
        description: "Choix du déploiement"
        required: true
        type: choice
        options:
          - develop
          - pre-prod
          - prod
        default: develop

jobs:
  gitHubInfos:
    name: Get GitHub infos
    runs-on: ubuntu-latest
    steps:
      - name: "git hub details"
        id: github_details
        shell: bash
        run: |
          echo ${GITHUB_CONTEXT}

        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha}}

      # ✅ Ajout du cache pour node_modules
      - name: Cache des dépendances Node
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install node modules
        id: installNodeModules
        shell: bash
        run: |
          npm install

      - name: Afficher les entrées utilisateur
        shell: bash
        run: |
          echo "📦 Environnement choisi : ${{ github.event.inputs.environment }}"

      - name: run project
        id: runProject
        shell: bash
        env:
          PORT: ${{ vars.PORT }}
        run: |
          node index.js &
          sleep 5
          curl -I http://localhost:${{ vars.PORT }}
          kill $(lsof -t -i:${{ vars.PORT }})
